---
permalink: protect-scw/concept_how_snapcenter_backs_up_windows_file_systems.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'O SnapCenter usa a tecnologia de cópia Snapshot para fazer backup dos recursos do sistema de arquivos do Windows que residem em LUNs, CSVs (volumes compartilhados de cluster), volumes RDM (mapeamento de dispositivos brutos), ALM (mapeamento de LUN assimétrico) em clusters do Windows e VMDKs baseados em VMFS/NFS (VMware Virtual Machine File System usando NFS).' 
---
= Como o SnapCenter faz backup dos sistemas de arquivos do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa a tecnologia de cópia Snapshot para fazer backup dos recursos do sistema de arquivos do Windows que residem em LUNs, CSVs (volumes compartilhados de cluster), volumes RDM (mapeamento de dispositivos brutos), ALM (mapeamento de LUN assimétrico) em clusters do Windows e VMDKs baseados em VMFS/NFS (VMware Virtual Machine File System usando NFS).

O SnapCenter cria backups criando cópias Snapshot dos sistemas de arquivos. Os backups federados, em que um volume contém LUNs de vários hosts, são mais rápidos e eficientes do que os backups de cada LUN individual, porque apenas uma cópia Snapshot do volume é criada em comparação com snapshots individuais de cada sistema de arquivos.

Quando o SnapCenter cria uma cópia Snapshot, todo o volume do sistema de storage é capturado na cópia Snapshot. No entanto, o backup é válido apenas para o servidor host para o qual o backup foi criado.

Se os dados de outros servidores host residirem no mesmo volume, esses dados não poderão ser restaurados a partir da cópia Snapshot.


NOTE: Se um sistema de arquivos do Windows contiver um banco de dados, o backup do sistema de arquivos não será o mesmo que o backup do banco de dados. Para fazer backup de um banco de dados, você deve usar um dos plug-ins do banco de dados.
