= 
:allow-uri-read: 


Você pode usar a convenção de nomenclatura de cópia Snapshot padrão ou usar uma convenção de nomenclatura personalizada. A convenção de nomenclatura de backup padrão adiciona um carimbo de data/hora aos nomes de cópia Snapshot que o ajuda a identificar quando as cópias foram criadas.

A cópia Snapshot usa a seguinte convenção de nomenclatura padrão:

`resourcegroupname_hostname_timestamp`

Você deve nomear seus grupos de recursos de backup logicamente, como no exemplo a seguir:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
Neste exemplo, os elementos de sintaxe têm os seguintes significados:

* _dts1_ é o nome do grupo de recursos.
* _mach1x88_ é o nome do host.
* _03-12-2015_23.17.26_ é a data e o carimbo de data/hora.


Como alternativa, você pode especificar o formato do nome da cópia Snapshot enquanto protege recursos ou grupos de recursos selecionando *usar formato de nome personalizado para cópia Snapshot*. Por exemplo, customtext_resourcegroup_policy_hostname ou resourcegroup_hostname. Por padrão, o sufixo do carimbo de hora é adicionado ao nome da cópia Instantânea.
